#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq2sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mydb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttblnot(tblnot instance);
    partial void Updatetblnot(tblnot instance);
    partial void Deletetblnot(tblnot instance);
    partial void Inserttblogr(tblogr instance);
    partial void Updatetblogr(tblogr instance);
    partial void Deletetblogr(tblogr instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::linq2sql.Properties.Settings.Default.mydbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblnot> tblnots
		{
			get
			{
				return this.GetTable<tblnot>();
			}
		}
		
		public System.Data.Linq.Table<tblogr> tblogrs
		{
			get
			{
				return this.GetTable<tblogr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblnot")]
	public partial class tblnot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ogrnumara;
		
		private string _dersadi;
		
		private System.Nullable<int> _sinavnot;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnogrnumaraChanging(System.Nullable<int> value);
    partial void OnogrnumaraChanged();
    partial void OndersadiChanging(string value);
    partial void OndersadiChanged();
    partial void OnsinavnotChanging(System.Nullable<int> value);
    partial void OnsinavnotChanged();
    #endregion
		
		public tblnot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrnumara", DbType="Int")]
		public System.Nullable<int> ogrnumara
		{
			get
			{
				return this._ogrnumara;
			}
			set
			{
				if ((this._ogrnumara != value))
				{
					this.OnogrnumaraChanging(value);
					this.SendPropertyChanging();
					this._ogrnumara = value;
					this.SendPropertyChanged("ogrnumara");
					this.OnogrnumaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersadi", DbType="NChar(50)")]
		public string dersadi
		{
			get
			{
				return this._dersadi;
			}
			set
			{
				if ((this._dersadi != value))
				{
					this.OndersadiChanging(value);
					this.SendPropertyChanging();
					this._dersadi = value;
					this.SendPropertyChanged("dersadi");
					this.OndersadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinavnot", DbType="Int")]
		public System.Nullable<int> sinavnot
		{
			get
			{
				return this._sinavnot;
			}
			set
			{
				if ((this._sinavnot != value))
				{
					this.OnsinavnotChanging(value);
					this.SendPropertyChanging();
					this._sinavnot = value;
					this.SendPropertyChanged("sinavnot");
					this.OnsinavnotChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblogr")]
	public partial class tblogr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _isim;
		
		private string _soyisim;
		
		private System.Nullable<int> _numara;
		
		private string _sinif;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnisimChanging(string value);
    partial void OnisimChanged();
    partial void OnsoyisimChanging(string value);
    partial void OnsoyisimChanged();
    partial void OnnumaraChanging(System.Nullable<int> value);
    partial void OnnumaraChanged();
    partial void OnsinifChanging(string value);
    partial void OnsinifChanged();
    #endregion
		
		public tblogr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isim", DbType="NChar(20)")]
		public string isim
		{
			get
			{
				return this._isim;
			}
			set
			{
				if ((this._isim != value))
				{
					this.OnisimChanging(value);
					this.SendPropertyChanging();
					this._isim = value;
					this.SendPropertyChanged("isim");
					this.OnisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyisim", DbType="NChar(20)")]
		public string soyisim
		{
			get
			{
				return this._soyisim;
			}
			set
			{
				if ((this._soyisim != value))
				{
					this.OnsoyisimChanging(value);
					this.SendPropertyChanging();
					this._soyisim = value;
					this.SendPropertyChanged("soyisim");
					this.OnsoyisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numara", DbType="Int")]
		public System.Nullable<int> numara
		{
			get
			{
				return this._numara;
			}
			set
			{
				if ((this._numara != value))
				{
					this.OnnumaraChanging(value);
					this.SendPropertyChanging();
					this._numara = value;
					this.SendPropertyChanged("numara");
					this.OnnumaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinif", DbType="NChar(10)")]
		public string sinif
		{
			get
			{
				return this._sinif;
			}
			set
			{
				if ((this._sinif != value))
				{
					this.OnsinifChanging(value);
					this.SendPropertyChanging();
					this._sinif = value;
					this.SendPropertyChanged("sinif");
					this.OnsinifChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
